add task1 module3
js-tasks-ru/jsbasic-20230629_wolfviking pull request #4
Opened 2023-07-10 11:37 UTC by wolfviking1979

2023-07-10 11:38 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-07-10 19:10 UTC, SinimaWath requested changes

2023-07-10 19:10 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return names;
Давай тут используем `map`

2023-07-11 08:44 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-11 10:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-11 10:53 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-11 10:59 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-12 11:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-12 12:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-12 12:02 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-12 13:22 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-12 13:28 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-07-12 13:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-07-13 16:04 UTC, SinimaWath requested changes

2023-07-13 16:04 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return res.join("");
Здесь у тебя не проходят тесты

2023-07-13 16:04 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return names;
Когда используешь map, push не нужен: 


`return  users.map(el => el.name)`

2023-07-13 16:33 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-07-15 05:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-07-15 07:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-07-17 07:18 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-17 07:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-07-17 07:23 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-17 07:24 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-17 08:23 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-17 10:20 UTC, SinimaWath requested changes

2023-07-17 10:20 UTC, SinimaWath commented on 4-module/3-task/index.js
> +      trs[i].classList.add("unavailable");
Не проходит этот тест
    ✖ Проставит класс available/unavailable, в зависимости от значения атрибута data-available у ячейки Status
    
Скорее всего в этой строчке ошибка

2023-07-17 11:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-18 08:49 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-07-18 09:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-07-22 19:25 UTC, SinimaWath approved these changes
все круто!

2023-07-22 19:28 UTC, merged